name: Build LaTeX Document

on:
  push:
    tags:
      - "v*"
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Git Repository
        uses: actions/checkout@v2
      - name: Compile LaTeX Document
        uses: xu-cheng/latex-action@v2
        with:
          work_in_root_file_dir: true
          root_file: |
            src/main.tex
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            src/main.pdf
